task:
  name: MacOS
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  setup_script: |
    brew install rustup
    rustup-init --profile minimal --default-toolchain nightly -y

  script: |
    source "$HOME/.cargo/env"
    cargo build --release
